### ISSUE TITLE
Is chartsian library down?

### ISSUE THREAD

**Issue by nidhalkratos** [ConsoleTVs/Charts#1]
We noticed that our pipeline is failing, it depnds on ConsoleTVs/Charts, which in turns depend on chartisan/php library. 
The github chartisan account is not accessible 404, do you know if there is any work around ?

**Comment by arwinvdv** [comment]
Same here, missing here version 7.2

**Comment by tabacitu** [comment]
Indeed - v7 is down for now, but will be back up. If you're wondering why - the author got slapped with a trademark violation notice. See [this Twitter thread](https://twitter.com/seb_sebsn/status/1554847275423305729) for more info. It's a horrible thing to happen to you as an OSS maintainer, to have legal action threatened against you, when your only intention was to build free stuff for people. So please be mindful.

What I get from what Erik said:
- v6 will be back online faster, since it isn't affected (it's already up, only docs remaining);
- v7 will take a little longer to bring back online, since it needs a rename;

**Comment by charlie87041** [comment]
Same here, any workaround?

**Comment by tabacitu** [comment]
@charlie87041 
- for v6 you should be ok, for me it works now, just make sure you purge the Composer cache;
- for v7 no solution that I know of yet, no;

**Comment by ConsoleTVs** [comment]
Hey guys, sorry for all the trouble. As @tabacitu said, I got a trademark notice for the v7 / chartisan project. Therefore I had to shut down the entire project. The charts repository was indeed affected as well.

For the time being, I was able to get the Charts repository created after getting in touch with github (and lost all stars, tags and commits).

Therefore I could only publish v6.

V7 will never be recovered. Instead, I have already started working on what would have been v8. But I think this will be left in a new package. I will have more information on that as time moves on.

In the meantime, thanks a lot for the support. I am deeply sorry for v7 users, but there's no way I can republish that without dealing with namespace issues (where the trademark would apply).

To be fair, anybody with the v7 version are actually in danger as well as the trademark could be used against them. So that's why I had decided to just shut it down. Not only to protect myself but also businesses and individuals using it.

**Comment by HosamSaleh1** [comment]
And where's the api link for v6, the project keep crushing cause the api link in the composer.lock file.
Thanks in advance

**Comment by ConsoleTVs** [comment]
What's an API link?

The docs are here: https://charts.erik.cat/
And the project is still `consoletvs/charts` for v6.

**Comment by HosamSaleh1** [comment]
https://api.github.com/repos/Chartisan/Charts/zipball/fc73038a006ddc2d6b277b9567ee01c6272448b3
Try this link

**Comment by ConsoleTVs** [comment]
The v6 of this library does not involve anything related to the project `chartisan` that was shut down for a trademark notice. You probably used v7, and this will never be recovered. You should read my comment above.

**Comment by HosamSaleh1** [comment]
{
            "name": "consoletvs/charts",
            "version": "6.5.6",
            "source": {
                "type": "git",
                "url": "https://github.com/Chartisan/Charts.git",
                "reference": "fc73038a006ddc2d6b277b9567ee01c6272448b3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Chartisan/Charts/zipball/fc73038a006ddc2d6b277b9567ee01c6272448b3",
                "reference": "fc73038a006ddc2d6b277b9567ee01c6272448b3",
                "shasum": ""
            },
That's in composer.lock
And in composer.json 
"consoletvs/charts": "6.*",
It's v6 not 7

**Comment by ConsoleTVs** [comment]
The repository was changed to https://github.com/ConsoleTVs/Charts instead of https://github.com/Chartisan/Charts to avoid copyright claims. Please update your composer lock file!

**Comment by HosamSaleh1** [comment]
Okay I'll, and the other link, please find solution for that too.
And thank you.

**Comment by ConsoleTVs** [comment]
There is not going to be a solution. That package is using a trademarked name on the source code level. It is not coming back.

**Comment by arborrow** [comment]
What can we do to be supportive or helpful with getting v8 developed, tested and available?

**Comment by juanitocbsi** [comment]
Guys, I am using 6 but it is no longer working. Any ideas?

**Comment by tabacitu** [comment]
@juanitocbsi what do you mean by "_no longer working_"?

**Comment by juanitocbsi** [comment]
> @juanitocbsi what do you mean by "_no longer working_"?

Thanks! My pipeline is no longer deploying v6. I get a 404.

**Comment by techcodex** [comment]
Hi I tried to run this command
composer require consoletvs/charts:6.* 
but composer returns error **zsh: no matches found: consoletvs/charts:6.***
I whole project stop working after I run composer install because I was using this into my project any other ways how can I downgrade the package version so my web start working ?
I tried to change composer.json file and change the version from 7.* to 6.* but when I run composer install it stills return error.

**Comment by tabacitu** [comment]
Does it work after you run `composer clearcache`?

**Comment by StiaanBouwer** [comment]
Hi, I am also having trouble downgrading to version 6.

I am using Laravel v8 with Docker on PHP 8.

It seems after v7 has been taken down, all of my `php artisan` commands are failing with the following error message.

`Illuminate\Contracts\Container\BindingResolutionException
Target class [ConsoleTVs\Charts\Registrar] does not exist.`

I've already tried `composer clearcache`
Even after removing the library completely, and setting up the project from scratch I am still facing this issue.

Any help would be greatly appreciated!

**Comment by imanimanyara** [comment]
@ConsoleTVs anything we can do to help with v8 get backup online? production projects are massively failing.

**Comment by ConsoleTVs** [comment]
> @ConsoleTVs anything we can do to help with v8 get backup online? production projects are massively failing.

You mean v7? No. It will never be online again. It was using a trademarked name in the source code. There's no way to fix that.

As for a new release, it is possible we get a new version of this sooner or later. But the v7 won't come back.

**Comment by imanimanyara** [comment]
> > @ConsoleTVs anything we can do to help with v8 get backup online? production projects are massively failing.
> 
> You mean v7? No. It will never be online again. It was using a trademarked name in the source code. There's no way to fix that.
> 
> As for a new release, it is possible we get a new version of this sooner or later. But the v7 won't come back.

Thanks, @ConsoleTVs for the response. To be clear, I meant v8, do you have a timeline in mind? I have some spare time and would love to be of help.

**Comment by LeoColomb** [comment]
> It will never be online again. It was using a trademarked name in the source code.

@ConsoleTVs Maybe a dumb question, but is it not possible to simply find and replace the name in the whole source code?
If the _only_ problem is a word presence, it should be quite doable, right?

I mean the code base was really great, quite a significant number of projects was using it, and just only in this ticket we are already 3 people to offer our help to sort this out.

**Comment by ConsoleTVs** [comment]
> > It will never be online again. It was using a trademarked name in the source code.
> 
> @ConsoleTVs Maybe a dumb question, but is it not possible to simply find and replace the name in the whole source code? If the _only_ problem is a word presence, it should be quite doable, right?
> 
> I mean the code base was really great, quite a significant number of projects was using it, and just only in this ticket we are already 3 people to offer our help to sort this out.

It's a breaking change. Requires both, package name changes and namespace changes, therefore it is not really worth because the fix won't be easy and require changes to codebases, so there's no real benefit that I can see here. (and keep in mind this changes are also on the frontend packages as well, so a real mess here)



> > > @ConsoleTVs anything we can do to help with v8 get backup online? production projects are massively failing.
> > 
> > 
> > You mean v7? No. It will never be online again. It was using a trademarked name in the source code. There's no way to fix that.
> > As for a new release, it is possible we get a new version of this sooner or later. But the v7 won't come back.
> 
> Thanks, @ConsoleTVs for the response. To be clear, I meant v8, do you have a timeline in mind? I have some spare time and would love to be of help.

I am working on it on my spare time already. But I don't want to risk myself on saying timelines. I will for sure notify everybody using this lib when this happens as best as I can (twitter, here, readme, docs, etc).

**Comment by AllCdnBoy** [comment]
sounds like you might have some people that are willing to help.  Could you create a private git ,and invite people that are interested in helping?

**Comment by Okipa** [comment]
There is a workaround that can be quickly set up for v7 users, in order to continue to use the package as is, as long as the v8 has not been released :

* Locally copy the `vendor/consoletvs` and `vendor/chartisan` directories in a new `packages` directory (positioned at the root of your project), to get the following structure:
  * `./packages/consoletvs/charts`
  * `./packages/chartisan/php`
* Update the `./packages/consoletvs/charts/composer.json` and set `"chartisan/php": "@dev"` instead of a specific version number
* Update your `./composer.json` and set `"consoletvs/charts": "@dev",` instead of a specific version
* Add a the following instruction in your `./composer.json`, at the root of the json:

```json
    "repositories": [
        {
            "type": "path",
            "url": "./packages/consoletvs/charts"
        },
        {
            "type": "path",
            "url": "./packages/chartisan/php"
        }
    ],
```

The copied sources should be now used instead of the packagist or github ones.

**Comment by illusive-ch** [comment]
Are they any docs on downgrading from 7 to 6 ? Does not seem as simple as just requiring the old package.

**Comment by larsbo** [comment]
anybody has a dump of the package whos name must not be named? I literally migrated from v6 to v7 hours before the package was removed and the local dev copy is gone...

**Comment by maatien** [comment]
> anybody has a dump of the package whos name must not be named? I literally migrated from v6 to v7 hours before the package was removed and the local dev copy is gone...

https://send.vis.ee/download/51e4819612195bf6/#J2AKNpcYXgO7RrQoE0eDPw

**Comment by tomcrofty** [comment]
> Are they any docs on downgrading from 7 to 6 ? Does not seem as simple as just requiring the old package.

If I do recall correctly, v7 was a huge change of direction from v6, v6 didn't use Chartisan at all (pls no lawyers) and instead worked with ChartJS, FusionCharts, ECharts etc etc. What I'm trying to say is it wasn't just a version bump with some new features but almost a complete rewrite which will require you to re-work everything you did.

If anyone is interested, there isn't really a solid alternative to quickly generating charts in Laravel, I was thinking of creating something similar to V6 using exclusively ApexCharts

**Comment by dominik-eller** [comment]
I was using version 7 and now I want to downgrade to 6 before you release version 8.

I am getting the following error:
Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Route [charts.***] not defined

In Version 7 I was registering the charts in the AppServiceProvider Class using the ConsoleTVs\Charts\Registrar

what do I need to do now?

**Comment by dominik-eller** [comment]
Any idea when v8 will be released?

**Comment by akiraaisha** [comment]
> Any idea when v8 will be released?

v8 release?😊
