### ISSUE TITLE
donut chart with dynamic value

### ISSUE THREAD

**Issue by robertnicjoo** [ConsoleTVs/Charts#213]
Hi,
I want to know how can I get donut chart with dynamic values? I like to get the number of my users & admins with that?

```
Charts::create('donut', 'highcharts')
  ->title('My nice chart')
  ->labels(['First', 'Second', 'Third'])
  ->values([5,10,20])
  ->dimensions(1000,500)
  ->responsive(false);
```

**Comment by ConsoleTVs** [comment]
->labels(['First', 'Second', 'Third'])
->values([5,10,20])

Theese are arrays...... do you really need me to explain what is it?

**Comment by robertnicjoo** [comment]
@ConsoleTVs I know what are those! The only reason i share those is to others can help me easily (doesn't need to go to documents page and see the codes), as a developer i suggest you to answer people if you know the answer, not to make fun of em! and if you don't know the answer just leave it alone maybe someone else knows.

**Comment by ConsoleTVs** [comment]
Hello, im not making fun of you, im a student and in my final exams! Please consider readingthe docs before asking since im the o ly dev for this library and sometimes answering things that are explained is not very good for me aince i have really few time to work on projevts like this.

To make dynamic values just get, for example, the data array you need like this:

Imagine you have a relationship on the user model that would return the blog posts a user have. And you would like to create a chart where the X (labels) would be every admin (admin is a boolean in db) (consider there are few admins) and values is the ammount of posts each admin have. Lets see:

```
$labels = User::where('admin', 1)->get();
$values = collect([]);
$labels->each(function ($user) {
    $values->push($user->posts->count());
});
// Here u have dynamic labels and values for the chart :)
```
