### ISSUE TITLE
multiple groupBy for pie chart?

### ISSUE THREAD

**Issue by vesper8** [ConsoleTVs/Charts#230]
Imagine a table for a dating site that has the fields gender and interested_in

gender can be either 'male' or 'female'
interested_in can be either 'male', 'female' or 'both'

Right now I am using two pie charts to show this because i can't figure out how to use a single pie chart to show all 6 combinations

I tried using multiDatabase but I think that doesn't work at all on pie charts? In any case I wasn't able to get it to work

Is it possible to achieve this with a single pie chart? If so can someone share how to set up the chart for this?

Thanks!

**Comment by ConsoleTVs** [comment]
Well pie charts cannot be multiple, simply because there are not multiple datasets. Apart from this, pie charts are designed to constrast diferent labels in the same field, in your case, genders != interesteds_in, so they are 2 diferent things, combining them I don't see a point.

If you still want to do it: Something people forget that the database and realtime for instance, are *helpers*. The base Charts::create method accepts any kind of array. So your option would be the following:

Create 2 arrays and combine it like this:

$values = [10, 20, 12, 12, 6];
$labels = ['male', 'female', 'Interested in man', 'Interested in female', 'Interested in both'];

You have to replace the values data with the total count in your database using eloquent or the query builder. After you got theese 2 arrays you can simply call the create method with theese values.
