### ISSUE TITLE
Method to hide dataset labels

### ISSUE THREAD

**Issue by JapSeyz** [ConsoleTVs/Charts#237]
Hey, I am looking for a way to hide dataset labels, (this example is for ChartJS, but is exactly what I am after)

https://stackoverflow.com/questions/37204298/chart-js-v2-hide-dataset-labels

Would you be willing to implement a method for hiding the dataset label while maintaining the hover effect?

**Comment by ConsoleTVs** [comment]
That's user-independent stuff. In fact, you're allowed to publish the assets and modify (or even add) new chart templates to it.

My suggestion to you is:

Publish the assets => Duplicate the chart type you want (eg: line) => rename it to something like: line-nolabels => modify the JS to remove labels => call it typing line-nolabels in the chart type instead of line.

The reason why I won't implement this is because not all libraries support removing or even having labels.
