### ISSUE TITLE
Database charts doesn't have any error but it does not render charts

### ISSUE THREAD

**Issue by krakenlabat** [ConsoleTVs/Charts#258]
My blade doesnt render the chart. What am I missing? Can someone look at my codes.

This is my table:
```
---------------------------------------------------------------------
name : Soda
---------------------------------------------------------------------
Doge    : 3
Doge 2  : 1
Doge 3  : 1
Doge    : 1
Doge 3  : 3
----------------------------------------------------------------------
```
Controller:
```
public function index()
    {
        $chart = Charts::multi('bar', 'highcharts')->labels(Product::all()->unique('Soda'));
        foreach(Product::all()->unique('name') as $name)
            {
                $data1 = Product::where('name', $name)->get()->pluck('Soda');
                $f_data1 = [];
                for($i= 0; $i<count($data1); $i++)
                {
                    $value1 = $i != 0? $data1[$i] + $data1[$i - 1] : $data1[$i];
                    array_push($f_data1, $value1);
                }
                $chart->dataset($name,$f_data1);
            }
        return view('chart', ['chart' => $chart]);
    }
```

Blade:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>My Charts</title>

        {!! Charts::styles() !!}

    </head>
    <body>
        <!-- Main Application (Can be VueJS or other JS framework) -->
        <div class="app">
            <center>
                {!! $chart->html() !!}
            </center>
        </div>
        <!-- End Of Main Application -->
        {!! Charts::scripts() !!}
        {!! $chart->script() !!}
    </body>
</html>
```
The desired output should look like this:
![123123123](https://user-images.githubusercontent.com/32327957/31043230-2d5e49ba-a5eb-11e7-90ab-d5da80108af3.JPG)

It just loads the view and it doesn't show the charts

**Comment by Acurex** [comment]
Hello krakenlabat,

you've got some errors in your Controller.

Right at the beginning:
`$chart = Charts::multi('bar', 'highcharts')->labels(Product::all()->unique('Soda'));`
gives you an Eloquent-Collection back.
If you want your Labels similar to your Screenshot, you have to name them manually:
`$chart = Charts::multi('bar', 'highcharts')->labels(['Soda', 'Chips', 'Biscuit']);` - I used extra labels to match your screenshot

The next line:
`foreach(Product::all()->unique('name') as $name)`
also gives you a collection back, but you just want the names, so you have to use:
`foreach(Product::all()->unique('name')->pluck('name') as $name)`


Regarding your foreach-loop:
I took another road and made the database sum-up the values:
```
foreach(Product::all()->unique('name')->pluck('name') as $name)
{
	$data1 = Product::where('name', $name)->groupBy('name')->selectRaw('sum(Soda) as sumSoda, sum(Chips) as sumChips, sum(Biscuit) as sumBiscuit')->first()->toArray();
	$data2 = array_values($data1);
	$data3 = array_map(create_function('$value', 'return (float)$value;'),$data2);
	$chart->dataset($name,$data3);
		}
```
The first line inside the foreach-loop selects and groups the datas by name, then i use the database sum-function. I use first() because the result is inside an array and convert it with toArray() from the ObjectModel of Laravel to a simple array.
My result for $data1 looks like this:
`array(3) { ["sumSoda"]=> string(1) "4" ["sumChips"]=> string(1) "2" ["sumBiscuit"]=> string(1) "1" }`
As you can see it is an array of key value pairs (also my int-values get convertd to string).

In the next line i get rid of the key:
`$data2 = array_values($data1);`
My result for $data2 looks like this;
`array(3) { [0]=> string(1) "4" [1]=> string(1) "2" [2]=> string(1) "1" }`

The third line converts the strings back to number (in my case floats, but you can also get ints):
`$data3 = array_map(create_function('$value', 'return (float)$value;'),$data2);` - for floats
`$data3 = array_map(create_function('$value', 'return (int)$value;'),$data2);` - for ints
If you are using floats in your database, you won't need the third line, because floats aren't changed to strings - but i would leave it in, because you never know want will get changed in future.


I tested this with a simple database and it worked. I'm aware that this is not the finest solution for your problem - with array_values() and array_map() and all this.

**Comment by ConsoleTVs** [comment]
Seems fixed, thanks @Acurex

**Comment by krakenlabat** [comment]
@Acurex  wow! Thank God you are there yes it work just want i want it. And thank you very much for explaining it, I'm having trouble learning laravel because I don't really have that much background in PHP, I just crash coursed learning laravel because the management wants it.

Yes the dataset-command expects an array of values, but having trouble dissecting them.

Can you please tell me where did you get ->selectRaw, can't find it in Laravel docs.

Once again thank you bro, you just saved me. Hope I can give you h5

**Comment by Acurex** [comment]
@krakenlabat i'm happy it works for you. I found the information about selectRaw on StackOverflow - yes, i have to look up myself every twenty minutes because i'm also still a beginner with Laravel, PHP and the rest of it.
The Documentation of Laravel does not mention it, it is just explained in the [Laravel-API-Guide](https://laravel.com/api/5.5/Illuminate/Database/Query/Builder.html#method_selectRaw). It is an Eloquent-expression for DB::select(DB::raw(.....)).

**Comment by ConsoleTVs** [comment]
I would recommend you not to learn sql builder in laravel. Really vad practice. Use laravel ORM (eloquent)

**Comment by krakenlabat** [comment]
Yes. By looking up every twenty minutes what do you mean? Scanning the laravel documentation? 
Oh ok, thanks for the reference surely i will share this also to my co-developer didn't know they got that Eloquent expression I'm also looking for it eloquent base,

**Comment by krakenlabat** [comment]
@ConsoleTVs  yeah and also eloquent code looks really nice to look at it than sql builder.

**Comment by ConsoleTVs** [comment]
:)

**Comment by Acurex** [comment]
@ConsoleTVs , @krakenlabat i agree, the eloquent-orm is much nicer. I use it when it suits my problem.
But sometimes Eloquent does not deliver the right set of commands to communicate with the database.

I wanted to sum up on database-side in one step, but you can also do it on php side for each column

```
public function index()
    {
    	$columnLabels = ['Soda', 'Chips', 'Biscuit'];
    	$chart = Charts::multi('bar', 'highcharts')->labels($columnLabels);
        
		foreach(Product::all()->unique('name')->pluck('name') as $name) {
			$data1 = Product::where('name', $name)->get()->groupBy('name');
			$dataArray = [];

			for ($i=0; $i < count($columnLabels); $i++) {
				array_push($dataArray, $data1[$name]->sum($columnLabels[$i]));
			}

			$chart->dataset($name, $dataArray);
		}

		return view('chart', ['chart' => $chart]);
    }
```

Now i got rid of the 'bad' sql builder :)

**Comment by ConsoleTVs** [comment]
You can optimize ur query much more. Using collections the right way, it will be much easy :)

**Comment by krakenlabat** [comment]
@ConsoleTVs why does pie not working? @Acurex can you change the graph from bar to pie, and see if its same.

**Comment by Acurex** [comment]
@krakenlabat For Multidatasets only Line, Bar and Area are working (see the documentation). It would be impossible to show Soda, Chips and Biscuits in one Pie. I think you will have to create individual Pie-Charts for Soda, Chips and Biscuits OR you could some up these three (Soda, Chips and Bisquits) for each Person to show the final amount in one Pie-Chart (Doge: 7 - 4 Soda, 2 Chips, 1 Bisquit; Doge 2: 4 - 1 Soda, ...)

**Comment by krakenlabat** [comment]
oh i see, sorry about that. So for now there's no support for Pie in database? But still can I achieve of rendering only the selled products and not the customer in Pie?

**Comment by ConsoleTVs** [comment]
You're missing the point.

create method is single dataset (pie supported)
databse is single dataset (pie supported)
multi is multi dataset (no pie)
multiDatabase multi dataset (no pie)

Check the official docs... there are examples :)

**Comment by krakenlabat** [comment]
Ohh that's a bummer sorry bout that, i'm so crowded right now. didn't see the database chart for it, maybe in the future you can add the multidaset for pie? hehe

**Comment by ConsoleTVs** [comment]
There's no way a pie chart can have more than 1 dataset... What should it be the result? haha

**Comment by Acurex** [comment]
@krakenlabat you can only split up the three sub-bar-charts (so to say) in three pie-charts. It could look like this:
![screenshot-2017-10-6 my charts 1](https://user-images.githubusercontent.com/9011225/31277085-81d98a1e-aa9f-11e7-9351-2f30693f1a82.png)

The controller could look like this:
 ```
    public function index4() {
		$columnLabels = ['Soda', 'Chips', 'Biscuit'];
		$charts = [];

		for ($i=0; $i < count($columnLabels); $i++) {
			$charts[$i] = Charts::create('pie', 'highcharts')->title($columnLabels[$i]);
			$dataArray = [];
			$labelArray = [];

			foreach(Product::all()->groupBy('name') as $name) {
				$add = 0;

				for ($j=0; $j < count($name); $j++) {
					$add += $name[$j]->{$columnLabels[$i]};
				}

				array_push($dataArray, $add);
				array_push($labelArray, $name[0]->name);
	 		}

	 		$charts[$i]->values($dataArray)->labels($labelArray);
		}

		return view('charts', ['charts' => $charts]);
	}
```

I used a new view-blade (charts.blade.php) to arrange the three pie-charts:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>My Charts</title>

        {!! Charts::styles() !!}

    </head>
    <body>
        <!-- Main Application (Can be VueJS or other JS framework) -->
        <div class="container">
            @foreach($charts as $chart)
            <div style="float: left; width: 33%">
                {!! $chart->html() !!}
            </div>
            @endforeach
        </div>
        <!-- End Of Main Application -->
        {!! Charts::scripts() !!}
        @foreach($charts as $chart)
        {!! $chart->script() !!}
        @endforeach
    </body>
</html>
```

I'm not sure if there is a cleaner or easier way to show three pie-charts in a view, but it works ;)
