### ISSUE TITLE
Dependency footprint

### ISSUE THREAD

**Issue by gsabater** [ConsoleTVs/Charts#316]
Hello,

I have been looking at the dependencies for this package, and one of those is "umpirsky/language-list".
This dependency only has a list of languages, but has more than 5000 files and 500 folders in 100MB of data, only for a list of languages.

Do we really need this dependency?
I think that this needs to be changed to something with less footprint.

**Comment by ConsoleTVs** [comment]
This is not from charts:
https://github.com/ConsoleTVs/Support/blob/master/composer.json#L18

Althought, you're lucky I'm the owner as well :)

Will take a look into it. But charts require Support atm.

As a matter of fact, I advise you not to take it too deep since I'm changing all the charts library. Check the readme on section "Important News"

**Comment by gsabater** [comment]
Yes, i have already seen that the whole library is being changed, but for someone that needs to install charts today, "support" and it's dependencies are added to that project, and i think that as for today, this is not necessary nor optimum.

I just wanted to give my opinion about that huge dependency, so i will be closing the issue.
Salut

**Comment by ConsoleTVs** [comment]
I will take it into consideration, thanks!
