### ISSUE TITLE
Realtime charts not working 

### ISSUE THREAD

**Issue by TangeniThePyGuru** [ConsoleTVs/Charts#321]
// this is my api route and it works

Route::get('/realtime',function (){
    $total_messages = 0;
    foreach (\App\YearlyMessages::all() as $message){
        $total_messages += $message->total_messages_for_the_year;
    }
    return json_encode(['data' => $total_messages]);
});

// this is my chart object in my controller
$chart = Charts::realtime(url('/realtime'), 1, 'area', 'highcharts')
            ->values([45])
            ->responsive(true)
            ->height(300)
            ->template("material")
            ->width(0)
            ->title("Real Time Outgoing Messages")
            ->maxValues(10)
            ->interval(3000)
            ->valueName('data')
            ->url(url('/realtime'));

// my view 
{!! $chart->html()  !!}

Where did i go wrong? please help!

**Comment by ConsoleTVs** [comment]
I'm afraid to tell you, that they did not work in the latest v.5 version because of a variable error. Since it was not fixed because a major breaking-change was in the way, it currently have no support at all. I don't honestly plan to fix it since it's probably not going to get more support. We will see how this goes... The v.6 is the way to go. Sorry for the issues. Realtime, AJAX, etc will come with v.6.

**Comment by TangeniThePyGuru** [comment]
Ok, When can we expect version v.6 be to be released?

**Comment by ConsoleTVs** [comment]
It is already :) not with this feature yet tho
