### ISSUE TITLE
Upgrade from 5.x version

### ISSUE THREAD

**Issue by jkudish** [ConsoleTVs/Charts#324]
Could you put together an upgrade guide from the 5.x version to the 6.x version? Seems like quite a lot changed and it'd be great to have a step by step guide to follow :)

**Comment by ConsoleTVs** [comment]
Hey! There's pretty much not an upgrade guide because every single aspect of the package is re-written from the ground up. There's pretty much everything to change. So I suggest your reading the new docs, understanding how the library will work from now on and change them once you can!

The reasons are simple:

- The library is now maintainable, there are almost no HTML views and it have 100% customization.
- It's much lighter overall and faster to use.
- Has nothing to do with 5.X version. 5.X was unsustainable and broken on it's core.

Sorry if that bothers you a bit but, the upgrade guide is, read the new docs and create the charts again with the php artisan make:chart command.

I hope you understand, let me know any questions!

**Comment by jkudish** [comment]
I'm happy you made so many improvements so it's worth the extra effort; just wanted to see if there was some magic trick. Will read through :)

**Comment by ConsoleTVs** [comment]
Aparently none of the syntax nor files where preserved, it's all 100% new. About the improvements, it's like atm there are fewer features than the 5.X version (as expected of a re-write) but at this point, it was worth to continue the development. As each charting library have a diferent class I can create presets and data modification for each library and avoid having one of the main problems I had in 5.X, people wanted lots of specific charting library features, and as a general chart class, it was impossible and ended up with tons of .html files... Hope you understand!
