### ISSUE TITLE
Start yAxes at 0

### ISSUE THREAD

**Issue by reinierkors** [ConsoleTVs/Charts#33]
Hi there, great package you made!

I was wondering if it's possible to start the graph at 0, like the setting for chartjs: beginAtZero to start the yAxes at 0.

**Comment by ConsoleTVs** [comment]
Hello @reinierkors Thanks a lot for the feedback! No, it's not posible at the moment and the reason is ovious, not all libraries support this. You're free to fork, modify and make a pull-request here with this feature if you wish to, otherwise I am planning (in a future) to handle options like that that might be available into diferent libraries!
