### ISSUE TITLE
Remove Nth axis label

### ISSUE THREAD

**Issue by brrn** [ConsoleTVs/Charts#334]
Charts v6.1.1
Library is Charts.js

I have a line chart with a time axis that shows 24 hours in the day, with grid lines every 15 minutes. I'd like to remove the incremental 15, 30, and 45 minute labels, but keep the hour labels in place. The only reference I can find on how to do this is by filtering the labels using the ticks callback.

http://www.chartjs.org/docs/latest/axes/labelling.html#creating-custom-tick-formats

Is it possible to use callbacks with this library? Can somebody give me an example?

Thanks!

**Comment by hichamhargal** [comment]
try to fix the xAxes value's unit by:
```
$chart->options([
    'scales' => [
        'xAxes' => [
            'type' => 'time',
            'time' => [
                    'unit' => 'hour'
                ]
        ]
    ]
]);
```

**Comment by ConsoleTVs** [comment]
It's not like if it's possible, thing about this:

Create a <script> tag with a variable that contains a function:

```javascript
var myCallback = function(value, index, values) {
    return '$' + value;
};
```

then in the code:

```php
$chart->options([
    'scales' => [
        'yAxes' => [
            [
                'ticks' => [
                    'callback' => 'myCallback'
                ]
            ]
        ]
    ]
]);
```

I think this would work... Haven't tested it tho

**Comment by brrn** [comment]
@hichamhargal If I set the time unit to hour, it will only show hour grid lines. I'd like to keep the 15min grid lines but only show labels on the hour.

@ConsoleTVs Thanks for the suggestion, but it doesn't seem to work. Charts.js spits out an error `TypeError: v is not a function`, which isn't very helpful.

**Comment by hichamhargal** [comment]
as you have a fixed time interval of 24 hours, I think you can use static labels for your X axe. something like this: 
```
$labels[] = "";
for($i = 1; $i<= 96; $i++){
	$h = $i%4;
	if($h == 0){
		$labels[] = $h." hours";
	}else{
		$labels[] = "";
	}
}

$chart->labels($labels);
```

NB: this code is not tested.

**Comment by balping** [comment]
@brrn 

> `TypeError: v is not a function`

This is because the callback you define is not an actual function, but a string as the array goes through `json_encode`. See my answer [here](https://github.com/ConsoleTVs/Charts/issues/369#issuecomment-386657051) on how to get around this.

@ConsoleTVs 

This can also serve as a general way to define callbacks. I might submit a PR on this.

**Comment by ConsoleTVs** [comment]
@balping Yeah go ahead :), I do not plan to support this feature, but the solution seems simple enough.

Try to encapsulate the PR tho, the trait can be merged into the original formatOptions from the base chart and the way to call the Raw object must be simple, perhaps create a new function in the base class called something like rawObject($argument) so that the result of your end code is this:

```php
'tooltip' => [
    'positioner' => $this->rawObject('positionerTooltip')
],
```
