### ISSUE TITLE
Highchart Pie colorByPoint

### ISSUE THREAD

**Issue by ale1981** [ConsoleTVs/Charts#345]
I can get other chart types (bar, column, line etc) to work but I can't seem to get the pie chart to display using different colours, the others work with the following code.

`        $this->options([
            'plotOptions' => [
                'series' => [
                    'colorByPoint' => true
                ]
            ])`

**Comment by ConsoleTVs** [comment]
$chart = new App\Charts\TestChart;
$chart->labels(['test11', 'test22', 'test33']);
$chart->dataset('Sample Test', 'pie', [3,4,1])
        ->color(['#00ff00', '#ff0000', '#0000ff']);

![image](https://user-images.githubusercontent.com/6124435/37420007-106fb0e4-27b6-11e8-803c-7ec5c895ba67.png)

**Comment by ale1981** [comment]
Thanks for the quick response, setting the colors worked, how come the pie chart doesn't work the same way as the other charts with colorByPoint?

**Comment by ConsoleTVs** [comment]
Pie charts have 1 dataset with n values. You aldo need n values for the colors. I made all pies and donuts data become correctly formated.

**Comment by LukaSikic** [comment]
Getting this unnecessary background on ChartJS.
![screen shot 2018-04-07 at 21 07 18](https://user-images.githubusercontent.com/15249077/38459324-880f2eae-3aa8-11e8-90b9-76a5139a9af4.png)

**Comment by ConsoleTVs** [comment]
Chartjs have color and backgroundColor... Please look the docs.

**Comment by LukaSikic** [comment]
Sorry, I'm ok with the color, but want to remove that graph in the background.

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/blob/master/src/Features/Chartjs/Chart.php#L42


..................................

**Comment by LukaSikic** [comment]
Sorry man, but try to improve the docs, I liked old version more since It was straight to the point and easy to use what at the end, should be the point of this package. Wish v5 is compatible with Laravel 5.6...

**Comment by ConsoleTVs** [comment]
V.5 is obsolete and it's because maitaining 15 libraries with the same code (that yea, simply to remember, works with everything) was easier. But at the same time, VERY limiting. Now you have 100% freedom. It's your choice to be limited and code easy or have freedom and a complete control of what you do.

Every charting library handles things differently. Even if you dislike it. I try to keep methods with the same names but as you may guess. some libraries make things hard to add a border color, a background color etc. That's why in some of them there's not that option.
