### ISSUE TITLE
Reload Chart via Ajax/API

### ISSUE THREAD

**Issue by petay87** [ConsoleTVs/Charts#373]
I have configured the charts package and so far all is working as expected. 

I am using Laravel 5.5 with version 6.1 of charts and I have used the controller to build the chart "template" and the api url to fetch and update the data for the chart. However, what I can't get to happen is to update the chart with new datasets via an Ajax or API call.

I can run an ajax and see that `return $chart->api();` is returning the correct dataset, in the same format that was sued to build the original chart, but I'm stuck trying to get this new data injected to the already rendered chart and then update the chart to display the new data. 

I've read through the V6 documentation as it was what allowed me to get as far as I have and I must say, it's really well written. However, I can't see anything in here explaining how to reload or refetch new data once the `{!! $chart->script() !!}` section has already been rendered. 

Can you or anyone else shed some light on this and point me in the correct direction or is this not possible?

**Comment by SavindaSenevirathne** [comment]
I have the same issue. Any luck

**Comment by ConsoleTVs** [comment]
Well, it's something that I will keep in mind for the next version but as a matter of fact, let me say that each chart have a JS variable declared in the window scope. That said, you just need to fetch the results and use the JS variable to change the data. This would require your to know how to manipulate rendered data in the chosen library, since they have diferent APIs

**Comment by ConsoleTVs** [comment]
The js variable stuff is documented

**Comment by pursehouse** [comment]
@ConsoleTVs I don't see how to get the name of the chart it creates in the js. It makes these random named variables like,
```
window.uxrsjkimzwpotyaedglbfcqvh = new Chart(
```

is there a access that name so that normal js code can be added to use that object?

**Comment by ConsoleTVs** [comment]
Documentation words:

"All charts are binded to a JS variable, by default, this variable is generated in the constructor, creating a random 25 characters long id with only lowercase alphabetic characters. This is the ID of the chart. If you ever need to modify the chart after it's rendered (eg: because you want to add, remove data) you may acces it in the window.{{ $chart->id }} JS variable."

**Comment by pursehouse** [comment]
oooh wonderful thanks, sorry I missed that

**Comment by Ahsankalim** [comment]
sir i faced that issues plz help me 
![capture1](https://user-images.githubusercontent.com/39775818/40800523-100fa850-652a-11e8-93fe-88e81dcd72cb.PNG)

**Comment by Mohammad-Yasin-Noori** [comment]
Your object creation should be from a Constructor at Line 14, it means you should add "()" after the Class name there.

**Comment by cdric0701** [comment]
Hello, thanks for this great library. Has someone an example on how to reload a chart with the ajax call ? thanks. I understand that we can access to {{ $chart->id }} but what can we do with that ?

**Comment by dily86** [comment]
I have the same issue and it's not working. Could you help me please ?

**Comment by ConsoleTVs** [comment]
You can use the js variable to reload the chart. The js variable contains the chart instance of thejs library u are using. You will need to know what method updates the chart. Check the docs of the given library.

**Comment by sardoj** [comment]
I just made a pull request which adds this feature.
See https://github.com/ConsoleTVs/Charts/pull/492

**Comment by thallessantos** [comment]
@sardoj sorry for my english, I hope you understand. The feature that you've implemented works fine, but when the data is modified and the chart should be load one or more "columns/bars", it doesn't. It only have the same bars of the first load.

**Comment by thallessantos** [comment]
> @sardoj sorry for my english, I hope you understand. The feature that you've implemented works fine, but when the data is modified and the chart should be load one or more "columns/bars", it doesn't. It only have the same bars of the first load.

I realized that issue it's because the _refresh method only updates data and options of the chart, but it should update the labels too.

**Comment by thallessantos** [comment]
@ConsoleTVs @sardoj I solved this with the code below, only to Chartjs because that's I used.

src\Features\Chartjs\Dataset.php
![Dataset](https://user-images.githubusercontent.com/13054457/57816041-38782e00-7750-11e9-9487-49d4d02517fc.png)

src\Views\chartjs\script.blade.php
![image](https://user-images.githubusercontent.com/13054457/57816076-56459300-7750-11e9-8d76-8ff4d5753bcb.png)

To use that it's just call the labels method after the dataset method.
![image](https://user-images.githubusercontent.com/13054457/57816265-0f0bd200-7751-11e9-88c8-9e0b50883d57.png)

I would like to see this little adjustment in the lib. :)

**Comment by vnandan** [comment]
> 
> 
> @ConsoleTVs @sardoj I solved this with the code below, only to Chartjs because that's I used.
> 
> src\Features\Chartjs\Dataset.php
> ![Dataset](https://user-images.githubusercontent.com/13054457/57816041-38782e00-7750-11e9-9487-49d4d02517fc.png)
> 
> src\Views\chartjs\script.blade.php
> ![image](https://user-images.githubusercontent.com/13054457/57816076-56459300-7750-11e9-8d76-8ff4d5753bcb.png)
> 
> To use that it's just call the labels method after the dataset method.
> ![image](https://user-images.githubusercontent.com/13054457/57816265-0f0bd200-7751-11e9-88c8-9e0b50883d57.png)
> 
> I would like to see this little adjustment in the lib. :)

This works perfectly!

**Comment by ConsoleTVs** [comment]
https://charts.erik.cat/api_charts.html#update-the-chart-after-rendering

**Comment by rafael1delgado** [comment]
> https://charts.erik.cat/api_charts.html#update-the-chart-after-rendering
BROKEN LINK!

**Comment by ConsoleTVs** [comment]
> 

https://v6.charts.erik.cat/api_charts.html#update-the-chart-after-rendering

**Comment by rafael1delgado** [comment]
> > 
> 
> https://v6.charts.erik.cat/api_charts.html#update-the-chart-after-rendering

The documentation is confusing to update the charts in version 6, they should improve it or include more examples.
