### ISSUE TITLE
Equivalent of Charts::database() in 6.*

### ISSUE THREAD

**Issue by jmebia** [ConsoleTVs/Charts#413]
Hi.

I'm having trouble figuring out the equivalent of Charts::database() from the older versions in the current version of Charts. Not sure if this is not yet in the current version or if I'm just missing something. Any help/guidance is greatly appreciated. Thanks

**Comment by ConsoleTVs** [comment]
It's not there. Im still unsure if this should be on it. You can use database data anyway. Why would you need that?

If you want examples follow the new docs found in here, there is an example that emulates the lastByDay stuff.

https://charts.erik.cat

Be aware that they are still under construction.

**Comment by jmebia** [comment]
Hi. Thanks a lot, I haven't seen that link you've sent before. Seems to have what I was looking for.

I guess I just got used to the old one too much. 

Thanks again!

**Comment by ConsoleTVs** [comment]
Yeah, It's the first time I publish it. It needs to be finished, some links are broken but you get the idea ^^

I'll probably add similar stuff / helpers to do what you could with the old databse method. But the new 6.0 is a lightweight version of the old one and it's actually MUCH faster to render the chart and supports 100% of the API of the chosen JS library. The published docs are bad and that's why I created the one I told ya ^^
