### ISSUE TITLE
[QUESTION] Can somebody help me with how to obtain certaint data?

### ISSUE THREAD

**Issue by mpixelz** [ConsoleTVs/Charts#424]
Hi,
are there any examples available for using v6? i mean ive gone through all the examples in the docs but those doesn't really solve what im trying to do.. previously i used this code to render my chart.. now i have no clue how to do this with v6. any clues?
```
$studentchart = Charts::database(\Role::findOrFail(2)->users, 'line', 'chartjs')
                ->title('')
                ->elementLabel("Students")
                ->responsive(false)
                ->colors(['#00c0ef'])
                ->dateColumn('created_at')
                ->lastByMonth(12, true);
```
and what is the use of creating the class as we are not even using it other than calling it in new ClassName?
sorry if i sound noob :(

**Comment by ConsoleTVs** [comment]
Because you can customize the chart directly. For example; creating a chart named LineChart, adding all the colors, styles and appearance and finally calling it X times with the new LineChart and just add the data, all the line charts will then look the same.

I've removed the database options in v.6. You're using PHP and that means you should know PHP enough to get the result by yourself. Can you get the users of the last 12 months in the role with id = 2 in a PHP array or laravel collection? If so, you can already do it.

I explain how to work with the database here: https://charts.erik.cat/adding_datasets.html#database-eloquent-example

If you have no clue how to get the data in an array it's not an issue with this library but with your skills.

However, helpers like that will likely be included in a future in this library as they are often used but keep in mind it's not a priority because this is just out of scope for this library's purpose. The purpose is to generate a chart, not to generate the data itself.

**Comment by mpixelz** [comment]
i can agree on that of my skills not being good as im self taught learning as i go..
i would really appreciate if you can help on this? 
this is just a default laravel installation with users table.. how can i draw users registered on a line chart for the last 12 months grouped in months? only one example will help me understand alot. months on x-axis and count on y-axis.
