### ISSUE TITLE
how to show multiple values in point hover 

### ISSUE THREAD

**Issue by lherreranetlink** [ConsoleTVs/Charts#462]
I'd like to know if there is an option created for showing multiple values on each tooltip (). Basically, I'd like to have something like this:

http://jsfiddle.net/jordanwillis/dzdm64wq/2/

Since now It only shows the title of the dataset and the value but I'd like to add more values on it.
I've been reading the documentation and it says it is possible to add every option like in javascript as long as the front end library allows it. But in my case I'm using Charts JS. How I'm i supposed to pass a function as a paremeter (Like in javascript where you can configure the what i want with a callback), or more precisely , How am i supposed to add more than one value on each tooltip of my Chart. 

I hope you can understand, I'm really struggling with this and i really need it for my project.

**Comment by Zontir** [comment]
I also have the same doubt. 
The package may be fine, but the ducumentation is super incomplete and very short, without examples.

**Comment by vesper8** [comment]
am struggling to accomplish the very same.. and asking myself the same questions as you @lherreranetlink 

did you happen to figure it out? Would love to know how you managed.. thanks!

**Comment by ConsoleTVs** [comment]
I think you guys miss the point of the library. Let me link the docs again: https://charts.erik.cat/customize_charts.html#generic-customization

Charts accepts what's said to be the whole JS library API. That means that you can inject any option to the chart configuration directly with PHP. For example, Imagine you want to set a generic config of the Echarts library. In this example you'll see how to enable/disable the chart tooltip based on the API Echarts provide.

The specified option is: https://ecomfe.github.io/echarts-doc/public/en/option.html#tooltip.show
You can use the options() method on the chart instance to setup any API settings you wish. As the API docs tell you, you need to set to true or false the option found in tooltip.show. To do it, simply call the options with the settings.

What's not clear about that that really makes everybody ask me how to do X thing with Y library? You can literally do ANYTHING supported in their API lol.

Your issue is about if ChartJS can display multiple values in a tooltip, well, I dont know, can it? If so, just look how it's done using their API and inject it using ->options().

**Comment by vesper8** [comment]
@ConsoleTVs I understand that we can add "anything" to the options returned from the php. However this appears to be adding some limitations. In this case for example in order to add more values to the tooltips it's necessary to use a javascript callback function.. something like this (code irrelevant)

```
                callbacks: {
                    beforeFooter: function(tooltipItems, data) { 
                      return 'Point #: ' + footerLine1[tooltipItems[0].index];
                    },
                    footer: function(tooltipItems, data) { 
                      return 'Other Data: ' + footerLine2[tooltipItems[0].index];
                    }
                }
```

The point is, we have not been able to figure out how (or if it's even possible) to return a javascript callback function that is set in a php controller, or in my case since I use the API, how to return a javascript callback function through json that will actually act as a javascript function once it is parsed and passed to the chart configuration on the front-end side. I don't think that's possible?

Also.. a bit off topic but I've been trying to get C3 charts to work and the way that your ->datasets methods work currently is not at all compatible with the way C3 expects its data to be formatted (it uses groups and columns which is syntax that is not at all present in your C3 datasets methods)

**Comment by Naoray** [comment]
@vesper8 maybe this is of help #369 for your callback issue

**Comment by vesper8** [comment]
thank you @Naoray ! https://gitlab.com/balping/json-raw-encoder does indeed look like what I need to enable php to pass js function callbacks via json!

**Comment by ConsoleTVs** [comment]
https://github.com/ConsoleTVs/Charts/blob/master/src/Classes/BaseChart.php#L306
