### ISSUE TITLE
How to customize Chart classes?

### ISSUE THREAD

**Issue by Fieel** [ConsoleTVs/Charts#507]
I started using this library thanks to this awesome video made by the author: https://www.youtube.com/watch?v=KrAvrU2XYuY

As soon as I checked the (newly updated) docs, everything was different.

First of, there is no info whatsoever on how to use the chart classes. We're currently using the classes to do the same logic we did when we used the Charts::create() method but instead we're using a useless class in-between now, I say useless because nowhere is to be found any info on how to customize this class or what its purpose is.

If I have to use classes, I'd love to customize them and use them in a way that makes sense and is different one class from the other. Basically, the repo lacks any documentation on this, or I simply missed it?

**Comment by ConsoleTVs** [comment]
Hello @Fieel , Thanks for the comment, here's my 2 cents:

> First of, there is no info whatsoever on how to use the chart classes

It's a PHP class, no magic involved, since the class inherits a base class, it comes with some methods that help you customize it. They are documented here: https://charts.erik.cat/create_charts.html#charts-api

> We're currently using the classes to do the same logic we did when we used the Charts::create() method but instead we're using a useless class in-between now, I say useless because nowhere is to be found any info on how to customize this class or what its purpose is.

The purpose of the class is to avoid repetition. When you work in a big project, this syntax repeats a lot, making it hard to code (or at least too much code to be repeated). Using classes allows to define (for example) a class that renders a a line chart with a given props, colors, shape, etc depending on some data, that way you can have a custom class that is a real representation of a "line chart" (for example) styled as you want. The `options` method is basically passed to the JS frontend you want as explained here: https://charts.erik.cat/customize_charts.html#generic-customization

> If I have to use classes, I'd love to customize them and use them in a way that makes sense and is different one class from the other. Basically, the repo lacks any documentation on this, or I simply missed it?

I think you missed it, but I'm always happy to answer things here :)
The thing again, is that the customization you want, is probably depending on the frontend JS lib you use.

The new version also allows for infinite number of datasets to be added. This means that each chart is not always multi dataset. Each dataset can also be configured as your need.

> Extra

Since people want to use this lib to avoid reading other docs, I've pulled in some presets for you to use.

Chart presets: https://charts.erik.cat/customize_charts.html#frappe
Datasets presets: https://charts.erik.cat/customize_datasets.html#dataset-presets

> Use case

As the example I gave above about the line chart, you may (for example) accept the array of data in the class constructor and create the datasets with your own settings on the constructor to abstract this.
I think you miss the point of the classes but I hope you understand why now 👍

**Comment by ConsoleTVs** [comment]
Hello again @Fieel 

> Can you please provide an example class with customized options?

This is quite requested and it's true I've been delaying it for a long time. I may give it a shot. I was busy with my bachelor thesis (nuua.io).

> So, most of the time, I'm supposed to use the ->options() method to customize my charts, using the chosen library proprieties? Unless of course there's a preset for it, in which I can simply use the preset method?

Exactly!

> How can I use those presets while customizing my class? How can I set the color of a graph, for example, without calling ->color('#ff0000') everytime I'm declaring and using a new graph?

It is a php class, therefore you can use the class constructor to call your methods like:

```php
// Give it some options.
$this->options(...);
// Or use a preset as well (can be chained).
$this->presetName(...);
```

You can in fact do that just after this line: https://github.com/ConsoleTVs/Charts/blob/master/src/Commands/stubs/chart.stub#L16

> I'd love to use the classes as you said, there just aren't any examples not indications in the docs. Thank you for the awesome library by the ways!

I will try adding them, but this is also open source work. Consider helping if you feel like there's more information needed: https://github.com/ConsoleTVs/ChartsDocs

**Comment by Fieel** [comment]
Thank you for your support, now everything's clear!

I never contributed in a true open source project and this would be the first time, if you don't mind, I can try to update the docs with an example and create a Pull Request!

**Comment by ConsoleTVs** [comment]
> Thank you for your support, now everything's clear!

I'm happy about it :)

> I never contributed in a true open source project and this would be the first time, if you don't mind, I can try to update the docs with an example and create a Pull Request!

This will make me even  happier, and welcome aboard :)


If you have anything else you wanna know, just let me know :)

**Comment by Fieel** [comment]
I have one last question, what happened to the methods you used in your original video from 2016? Methods such as Charts::database(), Charts::multi()?

**Comment by ConsoleTVs** [comment]
Gonna cite again my 1st answer on this post:

> The new version also allows for infinite number of datasets to be added. This means that each chart is not always multi dataset. Each dataset can also be configured as your need.

Also, for the database method, this must be done manually now. The reason is because I don't think it's the library's fault to format your data. This should come from your side. Two examples are provided here: https://charts.erik.cat/adding_datasets.html#database-eloquent-example

Maybe they will be re-introduced in the future :)
