### ISSUE TITLE
[BUG] Reload Chart Via Ajax => changing url parms not affected

### ISSUE THREAD

**Issue by abdosaeedelhassan** [ConsoleTVs/Charts#570]
**Required information**
 - Charts Version [6]
 - Laravel Version [6]
 - PHP Version [ 7.2]
 - Frontend JS Library Used:  [ Chart.js]

i already used documented api at 
https://charts.erik.cat/api_charts.html#building-the-chart

i used as follows:

var parm1='value';
var parm2='value';
 var timer = setInterval(function () {
{{ $chart->id }}_refresh(url+'?parms1='+parm1+'&parm2='+parm2);
console(parm1,parm2)
}, 5000);

it worked correctly with initial value of parms, but when changed give same data, outputing values of parms in console worked correctlly

**Comment by abdosaeedelhassan** [comment]
i think that the bug come from url generation, it repeated every load time as described in next vedio
https://www.loom.com/share/fe3fbffe171d4329a7bd49400d92e646

**Comment by ConsoleTVs** [comment]
Hello @abdosaeedelhassan. My recommendation is that you stop working on the charts using version 6. I'm going to release a new major record that is not compatible with the current one and this v.6 will not be maintained. The new version have this available out of the box implemented by me instead of a community member (as in the feature you're currently looking at).

**Comment by abdosaeedelhassan** [comment]
i am watting for the new version, thank you

**Comment by ConsoleTVs** [comment]
Just delay the advanced chart features for a few days and you'll be able to use the new and improved version. Hope you don't have any deadlines soon!

**Comment by abdosaeedelhassan** [comment]
thank you for your attention, will wait for improved version

**Comment by ConsoleTVs** [comment]
Done in the new version
