### ISSUE TITLE
Keeps loading forever, with Vue.

### ISSUE THREAD

**Issue by LasanthaSudeera** [ConsoleTVs/Charts#579]
I followed the documentation, but the SampleChart keeps loading forever. Almost all of my frontend uses Vue.

One thing I noticed was if I comment out the Vue Initialization in Apps.js the chart loads as usual. 

I am using the latest version of Laravel, PHP 7.4.

Thanks.

**Comment by ConsoleTVs** [comment]
Paste a sample code here please.

laravel version? Laravel charts version? Selected frontend library?

**Comment by LasanthaSudeera** [comment]
Laravel Version:  7.15.0
Vue Version: 2.5.17
Laravel Chart Version: 7.0.3 (Installed Today)

**home.blade.php**

`@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div id="chart" style="height: 300px;"></div>

            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
<script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>

<script>
    const chart = new Chartisan({
      el: '#chart',
      url: "@chart('sample_chart')",
    });
</script>

@endsection`

**app.blade.php**

`<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    
    <script src="{{ asset('js/app.js') }}" defer></script>

    
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    
                    <ul class="navbar-nav ml-auto">
                        
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>

    </div>
    @yield('js')
</body>

</html>`

**Comment by LasanthaSudeera** [comment]
![2020-06-15-19-21-19](https://user-images.githubusercontent.com/19815215/84665579-9a036100-af3d-11ea-8620-1509155fa50b.gif)

Here is a gif.

**Comment by hmreumann** [comment]
How did you comment the Vue initialization??

"One thing I noticed was if I comment out the Vue Initialization in Apps.js the chart loads as usual."

I have the same problem.

Thanks anyway. Hernán.

**Comment by ConsoleTVs** [comment]
I hope you're all initializing any dom library (like this one) in the vue's mounted() method....... Otherwise it wil fail. Vue needs to call dom manipulation libs inside mounted.

**Comment by hmreumann** [comment]
Thank you for answering, this is the mounted method i found:

![imagen](https://user-images.githubusercontent.com/36493144/89739074-f2de0a00-da53-11ea-8189-4651fbe5dc5d.png)

That is what you mean?

I have the problem of infinite loading, using Laravel Charts 7.* and Laravel 7.* PHP 7.4. Followed the guide, but couldn't make it work.

**Comment by Golovior** [comment]
I had the same issue.  
Solved it as follows:  
  
- Added `@stack('head')` just before the `head` closing tag in app.blade.php  
- In the template itself i added 
```
@push('head')
<script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
<script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>
<script src="/js/chart.js"></script>
@endpush
```
- In chart.js (which is located in public/js) i make the chartisan call in a window.onload function.
```
window.onload = function() {
  var gettingUser = jQuery('#chart').data('user');
  const chart = new Chartisan({
    el: '#chart',
    url: "/api/chart/user_chart?user=" + gettingUser,
    hooks: new ChartisanHooks()
      .title('Position and score')
      .colors()
      .datasets(['line', 'line']),
  });
}
```  
  
As you can see, i written out the url in this file. I needed to, because this isn't parsed anymore and @chart doesn't work.  
To get the variables into it, i added them to the  #chart element as data. It is probably not the cleanest way, but it does work to append the variables.  
  
Like this, the graph is shown in the layout and it doesn't give the vue error.

**Comment by ConsoleTVs** [comment]
1. You have to use Vue's lifecycle methods (mounted) to call new Chartisan()
2. You are using JQuery + Vue ????????
3. No need for that onload function

**Comment by Golovior** [comment]
> 1. _You have to use Vue's lifecycle methods (mounted) to call new Chartisan()_
To be honest, this issue is the first mention of "mounted" that i see. I followed the guild on installing it in laravel, which does not mention this "mounted" function, i think.
> 2. _You are using JQuery + Vue ????????_
Now you mention it. It is odd, isn't it? I've been working with jQuery for over 5 years now, so when getting a data attribute from an element, it was done on the automatic pilot and apparently it works. I've not included jQuery myself into laravel, but apparently it is known?
> 3. _No need for that onload function_
I do need it if i place it in the header of the page. Otherwise it doesn't work because #chart doesn't exist yet.

**Comment by Golovior** [comment]
Been looking for the reason why jQuery does work, if i do not load it.  
Found the following reason in app.js  
```
    jQueryDetection: function jQueryDetection() {
      if (typeof $ === 'undefined') {
        throw new TypeError('Bootstrap\'s JavaScript requires jQuery. jQuery must be included before Bootstrap\'s JavaScript.');
      }
```  
  
Apparently jQuery is loaded because of bootstrap.

**Comment by ConsoleTVs** [comment]
Ha, you use the old bootstrap stuff. I understand.

**Comment by ConsoleTVs** [comment]
> To be honest, this issue is the first mention of "mounted" that i see. I followed the guide on installing it in laravel, which does not mention this "mounted" function, i think.

This is a JS library, working alone. That said, JS frameworks like React, Vue, etc. Have strict policy of how DOM manipulation libraries are loaded because well... They do DOM manipulation by themselves. In the case of vue, their docs say that the mounted() method is called after all the component has been rendered, that means it's safe to manipulate the DOM. You then need to call new Chartisan(), (eventually, a function call that manipulates the DOM by creating the chart) inside the mounted method.

I Just can't be adding tutorials for every single JS framework around, you're responsible of knowing how Vue works if you intend to use it, not me...?

> Now you mention it. It is odd, isn't it? I've been working with jQuery for over 5 years now, so when getting a data attribute from an element, it was done on the automatic pilot and apparently it works. I've not included jQuery myself into laravel, but apparently it is known?

It's odd yes. But required by the old Bootstrap stuff. I still don't know if that's 100% needed nowadays. There's no reason to use Jquery, specially if you're already using vue. http://youmightnotneedjquery.com/

> I do need it if i place it in the header of the page. Otherwise it doesn't work because #chart doesn't exist yet.

As I said, you need to call that in the vue's mounted() method of your component, or vue instance. Mounted makes sure to be called when the DOM is already there, window.onload is not safe, vue does more after the window is loaded, you're being lucky here if that works and it's just a matter of time for it to break again.

**Comment by Golovior** [comment]
I'll look into vue. Never used it before, so it will probably take some time to getting to know it. _Never used it before?_ Nope, never used it before. _Then why now?_ Probably because it is installed with Laravel at default?  
So I would have expected a mention of it in https://charts.erik.cat/  
Same with jQuery. I did not know it was installed when I used it. But Bootstrap is also installed at default with Laravel and because of it, it also installs jQuery probably.

**Comment by ConsoleTVs** [comment]
> Probably because it is installed with Laravel at default

https://github.com/laravel/laravel/blob/master/package.json#L12

It does not come by default.

You probably mean: laravel UI (https://laravel.com/docs/7.x/frontend)

And you can choose between: bootstrap, vue, react. Nothing comes by "default". If you choose to use vue, then you should learn vue. If you choose react, then you should learn react. Why do I have to keep track of the X options laravel offer as a **back-end** framework in their minimal and totally separated **front-end** section? It's your responsability to uninstall, or install things you want in your front-end. And well, if you're going to use a JS framework for UI like vue / react, then take into consideration that DOM manipulation libraries like this one will need to be called in their respective lifecycle methods. All frameworks have ways to do it, otherwise half JS frameworks would not be usable.

**Comment by ConsoleTVs** [comment]
In addition, I already made a React adapter, and the Vue adapter is on its way when vue 3 comes out.

Those adapters will allow you to use Chartisan with a single component call, and it will work out of the box because I already took care to initialize everything when the given frameworks wanted to.

React adapter: https://github.com/ConsoleTVs/ChartisanReact

**Comment by ConsoleTVs** [comment]
I've already used Chartisan in some production vue application without issues.

Nevertheless, I'll create a vue 3 adapter for Chartisan in the following months like I did with react.
