### ISSUE TITLE
Font-Size in the axes and position Legend

### ISSUE THREAD

**Issue by mafalda2007** [ConsoleTVs/Charts#585]
Hi, is it possible to change the fontsize of the axes?

Why doesn't the legend appear at the bottom?

```
    const chart = new Chartisan({
        el: '#chart',
        url: "@chart('resumen_chart')?value=" + 'VARIABLE',
        loader: {
                color: '#ff00ff',
                size: [30, 30],
                type: 'bar',
                textColor: '#000',
                text: 'Cargando los datos...',
            },
        responsive: true,
        datasets: 'line',
        hooks: new ChartisanHooks()
            .colors(['rgba(0,215,44,0.6)', 'rgba(10,15,4,0.6)'])
            .legend({ position: 'bottom' })
            .title('Titulo')
            // FontSize???
            .datasets(['line','line']) 
    });
```

**Comment by ConsoleTVs** [comment]
Yes it is. Will reply later with an example.

**Comment by ConsoleTVs** [comment]
First of all, all customizations like "responsive" or "datasets" that you have there must be in the hooks.

You can use the options() method to pass directly options to the charts like so:

```js
new ChartisanHooks()
  .options({ ... })
```

For example, for chart.js, you can se this: https://www.chartjs.org/docs/latest/general/fonts.html

First of all you can add a global font by importing Chart from chartjs and setting the default before the chartisan library loads. Otherwise, you can pass the options to the chart using .options() as mentioned above.

For the example they provide, you can change the font of specific elements by using options.legend.labels.fontColor

You can then do:

```js
new ChartisanHooks()
  .options({ options: { legend: { labels: { fontColor: '#ff0000' } } } } )
```
