### ISSUE TITLE
Followed the Guide and with the Sample Chart i get "Loading..."

### ISSUE THREAD

**Issue by hmreumann** [ConsoleTVs/Charts#613]
Hallo,

i followed the steps on the guide,

I have this error in the console, and infinite "Loading"

I think it might be the Vue problem, but i don't know how to solve it.

![imagen](https://user-images.githubusercontent.com/36493144/89733128-b39ac380-da29-11ea-83c0-6333b199d759.png)

Thanks anyway, Hernán.

**Comment by hmreumann** [comment]
I did it without the app layout and it worked. But, i lost the laravel template.
I don't know what is generating the problems over there.

**Comment by Golovior** [comment]
I had the same issue.  
Solved it as follows:  
  
- Added `@stack('head')` just before the `head` closing tag in app.blade.php  
- In the template itself i added 
```
@push('head')
<script src="https://unpkg.com/echarts/dist/echarts.min.js"></script>
<script src="https://unpkg.com/@chartisan/echarts/dist/chartisan_echarts.js"></script>
<script src="/js/chart.js"></script>
@endpush
```
- In chart.js (which is located in public/js) i make the chartisan call in a window.onload function.
```
window.onload = function() {
  var gettingUser = jQuery('#chart').data('user');
  const chart = new Chartisan({
    el: '#chart',
    url: "/api/chart/user_chart?user=" + gettingUser,
    hooks: new ChartisanHooks()
      .title('Position and score')
      .colors()
      .datasets(['line', 'line']),
  });
}
```  
  
As you can see, i written out the url in this file. I needed to, because this isn't parsed anymore and @chart doesn't work.  
To get the variables into it, i added them to the  #chart element as data. It is probably not the cleanest way, but it does work to append the variables.  
  
Like this, the graph is shown in the layout and it doesn't give the vue error.
