### ISSUE TITLE
Documentation not familiar for laravel

### ISSUE THREAD

**Issue by habibadnan6854** [ConsoleTVs/Charts#622]
I can't understand your Chartisan Documentation. I already saw many videos on youtube about laravel Chartisan, but they have different documentation and readable but I'm trying to find the exact documentation but it has none Maybe changed your documentation. Please provide me a laravel friendly documentation like before. Urgent needed

**Comment by WS243593** [comment]
Okay, so I pieced it together in my head; as cohesively as I can, I shall try to explain how to use it with Laravel. 

**To preface, you need to realise that Chartisan is treated as a sort of "core" to Laravel Charts. So consider that as almost an extension. With this in mind, there will be back and forth between https://chartisan.dev/ and https://charts.erik.cat/**
### Step 1 - Front-end

1. Head to https://chartisan.dev/ and click on _Getting Started._
2. **VERY IMPORTANT** On the top of the left sidebar there is a preferences area, make sure you double check that these are the environment variables that you are using, e.g. backend adapter: PHP, front-end: JS, chart: chartjs.
3. Head to the _Installing Adapters_ section. Here you have two options using NPM or CDN, I am using NPM so I will describe that, CDN is self-explanatory anyway. 
4. C/P this into your project CLI: `npm install chart.js @chartisan/chartjs` <--This tells your project what front-end charting tool you will use.

### Step 2 - Back-end

1. Head over to https://charts.erik.cat/
2. Under the _Installation_ section you will find two CLI commands, C/P both of them: 
`composer require consoletvs/charts "7.*"`
and
`php artisan vendor:publish --tag=charts`
3. Next go on over to _Create Charts_ section and use `php artisan make:chart SampleChart` (replace SampleChart with whatever you want your chart to be called) to create your chart php file as shown on the example. 
4. Follow the steps under the _Register the chart_ heading and make sure you run `php artisan route:list -c` command and note the URL for your chart, this will begin with api/chart/
5. At this stage you can mess with the chart configuration, but for now leave it as is unless you have some funky routing going on (can't help with that).

### Step 3 - Rendering Graph
**This is where things get a bit tricky if you are using NPMand webpack.mix.js, if you are using the CDN versions of things just C/P the ** _Render Chart_ ** example and you should be good to go. For NPM follow below:**

1. I recommend creating a standalone javascript file where you will be calling your charts. I called mine myCharts.js
2. Do not forget to include this at the bottom of your layout page like so:
`<script type="text/javascript" src="{{ asset('js/myCharts.js') }}"></script>`
3. Inside that file paste the following: 
`import { Chartisan } from '@chartisan/chartjs'`
`const chart = new Chartisan({`
   `el: '#chart',`
   `url: 'https://chartisan.dev/chart/example.json',`
   `// You can also pass the data manually instead of the url:`
   `// data: { ... }`
`})`
3.1 Couple of things to keep in mind, the `el:` is responsible for hooking onto the element on your blade file so if you kept the default id="chart", than keep the `el:` as is.
3.2 The route you got needs to go into the `url:` part as plain url. Do not use the `@chart` blade syntax, this will not render in your JS file.
4. Okay, so with all of the above done, this step should do it. Open your webpack.mix.js file and include your JS file under mix, then **VERY IMPORTANT** either run `npm run dev` for a single build instance or `npm run watch`
 for continuous building. 

**And that should do it, I really hope that whoever finds this will find it useful. If there is any confusion about the above just drop me a line and I'll try to help out. Cheers!**

**Comment by ConsoleTVs** [comment]
@WS243593 Thank you for your kind response.

I am considering the shift of this package to a fully backend controlled charts (as the versions from last year). Of course Chartisan still remains and can be used with the php adapter anyway. 

Feels like 85% of the devs using this lib have little understanding of frontend and only use blade. So its still a good use case for them. Will post some updates soon. Thank you again.
