### ISSUE TITLE
[QUESTION] Recommended way to export charts as an image?

### ISSUE THREAD

**Issue by waterbuckit** [ConsoleTVs/Charts#650]
I'm writing a reporting module for our web application and would like to use the charts generated via Chartisan/Charts.js using laravel charts as images in a PDF report. Is there some recommended way of exporting these? 

I understand it will probably involve accessing the canvas element and extracting the dataURL, but I wanted to know if any one else had done such a thing?

**Comment by ConsoleTVs** [comment]
I can providle little to no insight here. This depends in the selected front-end you want

In any frontend (Chartisan) instance, you can call `.chart` to get the underlying frontend chart instance.

Might be strange in some cases since the Chartisan instance is normally called chart too. `chart.chart`.

In echarts you can call: https://echarts.apache.org/en/api.html#echartsInstance.getDataURL

In chart.js you can call: https://www.chartjs.org/docs/latest/developers/api.html#tobase64image

Note that chartisan's chart.js does already have an undocumented helper for this:
https://github.com/Chartisan/Chartjs/blob/master/src/index.ts#L125

You can, therefore, call `chart.toImage()`.

In either case, I think the canvas needs to be created first. However, I think that echarts does support SVG too, so it might be worth to check it out.
