### ISSUE TITLE
Multi Datasets Charts

### ISSUE THREAD

**Issue by zorrigas** [ConsoleTVs/Charts#74]
Is possible create a Multi Datasets Charts from Database? 

Example:

` A Table
-------------------
| ID | name | type |
--------------------

B Table
--------------------------------
| ID | name | data | atable_id |
--------------------------------
 `
In Line or Bar Chart.

**Comment by ConsoleTVs** [comment]
Will do it before the release of the upcoming 3.0

**Comment by oceanapplications** [comment]
Have you been able to add this yet?  I didn't see it in the docs and it'd be super useful.

Thanks

**Comment by ConsoleTVs** [comment]
Not yet since I am still looking forward linking two charts. Database charts extends the base charts, multi datasets extends the base charts, so I have 2 extensions and i need a bit of each one, so kinda complicated :/ still looking forward it tho. It needs to be done manually meanwhile, creating the data yourself

**Comment by ConsoleTVs** [comment]
Should be done for 4.0.
